apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: location
    role: api
    tier: backend
    language: golang
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
  selector:
    app: location
    role: api
    tier: backend
    language: golang
  type: LoadBalancer
